package algorithms.project;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import static algorithms.project.EdgeInputFram.frame;
import static algorithms.project.EdgeInputFram.vs;
//import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import edu.uci.ics.jung.graph.SparseGraph;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Paint;
import java.awt.Stroke;
import java.awt.event.WindowEvent;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.collections15.Transformer;

/**
 *
 * @author Home
 */
public class DijkstraOutFram extends javax.swing.JFrame {

    /**
     * Creates new form OutPutFram
     */
    static DefaultTableModel model;
    public DijkstraOutFram() {
        initComponents();
        setLocationRelativeTo(null);
        visitedArr = new Vector();
        visitedArrBlue = new Vector();
        visitedArrGray = new Vector();
        vistedBool = false;
        count = 0 ;

        model = new DefaultTableModel();
        tableData.setModel(model);
        model.addColumn("Vertex Name");
        
        model.addColumn("Shortest Path From "+ ChooseFram.src);
        jLabel1.setText("The Shortest Path From "+ ChooseFram.src+ " to All Verteces");
        
        
//        for (int i = 0; i <ShortestPath.vertexNames.size() ; i++) {
            model.addRow(new Object[]{
                ShortestPath.vertexNames.get(0),
                ShortestPath.distance[0]
        
            });
//        }
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        closeBt = new javax.swing.JButton();
        backBt = new javax.swing.JButton();
        stepBystepBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stepBystepBt1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algorithms/project/source/abstract-geometric-shape-connection-with-3d-cubes-background_42705-105.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vertex Name", "Shortest Path From Source"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 163, 413, 124));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setText("The Shortest Path From Source to All Verteces");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        closeBt.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        closeBt.setForeground(new java.awt.Color(200, 0, 0));
        closeBt.setText("Exit");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });
        getContentPane().add(closeBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 113, -1));

        backBt.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        backBt.setText("Previous");
        backBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtActionPerformed(evt);
            }
        });
        getContentPane().add(backBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 113, -1));

        stepBystepBt.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        stepBystepBt.setForeground(new java.awt.Color(0, 0, 255));
        stepBystepBt.setText("Next Step");
        stepBystepBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepBystepBtActionPerformed(evt);
            }
        });
        getContentPane().add(stepBystepBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 105, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("To See Result step by step press Next Step");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 105, -1, 29));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("To See The Whole Result press Result");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 65, -1, 29));

        stepBystepBt1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        stepBystepBt1.setForeground(new java.awt.Color(0, 0, 255));
        stepBystepBt1.setText("Result");
        stepBystepBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepBystepBt1ActionPerformed(evt);
            }
        });
        getContentPane().add(stepBystepBt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 65, 113, -1));

        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jButton2.setText("New Input");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 130, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algorithms/project/source/abstract-geometric-shape-connection-with-3d-cubes-background_42705-105.jpg"))); // NOI18N
        jLabel5.setText("one by one");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        // TODO add your handling code here:
        System.exit(0);        
    }//GEN-LAST:event_closeBtActionPerformed

    private void backBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtActionPerformed
        // TODO add your handling code here:
        super.setVisible(false);
        ChooseFram chosF = new ChooseFram();
        chosF.setVisible(true);
        EdgeInputFram.frame.setVisible(false);
        EdgeInputFram.displayGraph();
    }//GEN-LAST:event_backBtActionPerformed

    private void stepBystepBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepBystepBtActionPerformed
        // TODO add your handling code here:
        if(count == 0){
            clearTable();
            model.addRow(new Object[]{
                ShortestPath.vertexNames.get(0),
                ShortestPath.distance[0]
        
            });
        }
        vistedBool = false;
        if(count < ShortestPath.map.size()){
            
            displayStepByStep();
            //System.out.println("suffix = "+suffix);
//            if(suffix != null){
//                model.addRow(new Object[]{
//                    suffix,
//                    ShortestPath.distance[ShortestPath.vertexNames.indexOf(suffix)]
//
//                });
//            }
            count++;
            
        }
        else{
            stepBystepBt.setText("Finished");
            stepBystepBt.setForeground(new Color(0,100,0));
            stepBystepBt.setEnabled(false);
            count = 0;
        }

    }//GEN-LAST:event_stepBystepBtActionPerformed
    public void clearTable(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); // notifies the JTable that the model has changed
        
        visitedArr  = new Vector<>();
        visitedArrBlue  = new Vector<>();
        visitedArrGray  = new Vector<>();
        count = 0 ;
        vistedBool = false;
        
        stepBystepBt.setText("Next Step");
        stepBystepBt.setForeground(Color.BLUE);
        stepBystepBt.setEnabled(true);
    }
    private void stepBystepBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepBystepBt1ActionPerformed
        // TODO add your handling code here:
        ChooseFram.displayDijkatra();
        
        clearTable();
        model.addRow(new Object[]{
                ShortestPath.vertexNames.get(0),
                ShortestPath.distance[0]
        
        });
        for (int i = 1; i <ShortestPath.arrangedEdges.length ; i++) {
            String str = (String) ShortestPath.arrangedEdges[i];
            System.out.println("Str = " + str);
            int spacePos2 = str.indexOf(" ");
            String suffix2 = str.substring(spacePos2 + 1, str.length()); //Gets the terminal
                                    
            model.addRow(new Object[]{
                //ShortestPath.vertexNames.get(i),
                //ShortestPath.arrangedEdges[i],
                suffix2,
                ShortestPath.distance[i]
        
            });
       }
    }//GEN-LAST:event_stepBystepBt1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //System.exit(0);        
        StartFrame stf = new StartFrame();
        stf.setVisible(true);
        //frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));

        
        //EdgeInputFram.frame.setVisible(false);
        EdgeInputFram.frame.dispose();
        frame.dispose();
        super.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public static void displayStepByStep(){
        Transformer<String, Paint> edgePaint = new Transformer<String, Paint>() {    
                    @Override
                    public Paint transform(String s) {    // s represents the edge
                            //String weight = s.replace("*", "");
                            //System.out.println(weight);
                            System.out.println("Map = "+EdgeInputFram.map.get(s));
                            String edgeInitAndTerm = (String) EdgeInputFram.map.get(s);
                            String edgeInitAndTerm2 = (String) EdgeInputFram.map2.get(s);

                            //System.out.println(ShortestPath.map.containsValue(EdgeInputFram.map.get(s)));
                            //System.out.println("ChooseFram = " + edgeInitAndTerm+"try");
                            //System.out.println("befor if = "+ edgeInitAndTerm ==(String) ChooseFram.shortPath.arrangedEdges[1]);
                            if(!visitedArr.contains(s) && !vistedBool 
                                    && ( edgeInitAndTerm.equals(ChooseFram.shortPath.arrangedEdges[count]) ||
                                    edgeInitAndTerm2.equals(ChooseFram.shortPath.arrangedEdges[count]))
                                    ){
                                visitedArr.add(s);
                                
                                System.out.println("in frist if ");

                                if (ShortestPath.map.containsValue(EdgeInputFram.map.get(s))||
                                      ShortestPath.map.containsValue(EdgeInputFram.map2.get(s))){
                                    visitedArrBlue.add(s);
                                    System.out.println("in second if ");
                                    //intiTerm = (int) ShortestPath.map2.get(EdgeInputFram.map.get(s));
                                    
                                    System.out.println("edgeInitAndTerm = "+edgeInitAndTerm);

                                    int spacePos = edgeInitAndTerm.indexOf(" ");
                                    suffix = edgeInitAndTerm.substring(spacePos + 1, edgeInitAndTerm.length()); //Gets the terminal
                                    
                                   
                                    
                                    model.addRow(new Object[]{
                                            suffix,
                                            ShortestPath.distance[count]

                                     });
            
                                    
                                    
                                    System.out.println("In Blue");
                                    vistedBool = true;
                                    //count++;
                                    return Color.BLUE;
                                }
                                else {
                                    //count++;
                                    visitedArrGray.add(s);
                                    System.out.println("In Gray");
                                    return Color.LIGHT_GRAY;
                                }
                            }
                            else if (visitedArrBlue.contains(s))
                                return Color.BLUE;
                            else if (visitedArrGray.contains(s))
                                return Color.LIGHT_GRAY;
                            else
                                return Color.LIGHT_GRAY;
                           
                        }
                    };
                    //vistedBool = false;
                        ///Change Edge Font 
                    vs.getRenderContext().setLabelOffset(20);
                    vs.getRenderContext().setEdgeStrokeTransformer(new Transformer<String,Stroke>(){
                       @Override
                       public Stroke transform(String s) {
                           return new BasicStroke(5);
                       }
                   });
                   vs.getRenderContext().setEdgeArrowStrokeTransformer(new Transformer<String,Stroke>(){
                       @Override
                       public Stroke transform(String s) {
                           return new BasicStroke(5);
                       }
                   });


                    EdgeInputFram.vs.getRenderContext().setEdgeDrawPaintTransformer(edgePaint);
                    //EdgeInputFram.vs.getRenderContext().setEdgeFontTransformer();

                    EdgeInputFram.frame.getContentPane().add(vs);
                    //frame = new JFrame();
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frame.pack();
                    frame.setVisible(true);
                    frame.setSize(500,400);
                    frame.setTitle("Shortest Path");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DijkstraOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DijkstraOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DijkstraOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DijkstraOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DijkstraOutFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBt;
    private javax.swing.JButton closeBt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton stepBystepBt;
    private javax.swing.JButton stepBystepBt1;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
    public static Vector<String> visitedArr ;
    public static Vector<String> visitedArrBlue ;
    public static Vector<String> visitedArrGray ;
    public static int count ;
    public static Boolean vistedBool;
    public static int intiTerm ;
    public static String suffix;
}
