package algorithms.project;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import edu.uci.ics.jung.algorithms.layout.CircleLayout;
import edu.uci.ics.jung.graph.DirectedSparseGraph;
import edu.uci.ics.jung.graph.SparseGraph;
import edu.uci.ics.jung.visualization.VisualizationImageServer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.Paint;
import java.awt.Toolkit;
import java.lang.reflect.Array;
import javax.swing.JFrame;
import org.apache.commons.collections15.Transformer;
import java.util.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;


/**
 *
 * @author Home
 */
public class EdgeInputFram extends javax.swing.JFrame {

    /** Creates new form EdgeInput */
    public EdgeInputFram() {
        initComponents();
        setLocationRelativeTo(null);
        finishBt.setEnabled(false);
        greenTx.setVisible(false);
        
//        Vector<String> vertices = new Vector<>();
//        vertices.add("a");
//        vertices.add("b");
//        vertices.add("c");
//        
//        VertexNameInputFram.g = new Graph(vertices);
//        VertexNameInputFram.g.vertexNum = 3;
//        
//        
//        VertexNameInputFram.g.addEdge("a", "b", 1);
//        VertexNameInputFram.g.addEdge("a", "c", 10);
//        VertexNameInputFram.g.addEdge("b", "c", 2);
//        
//        EdgeInputFram.directedGraph.addEdge("1","a","b");
//        EdgeInputFram.directedGraph.addEdge("10","a","c");
//        EdgeInputFram.directedGraph.addEdge("2","b","c");
//        
//        EdgeInputFram.map.put("1", "a b");
//        EdgeInputFram.map.put("10", "a c");
//        EdgeInputFram.map.put("2", "b c");

//        Vector<String> vertices = new Vector<>();
//        vertices.add("s");
//        vertices.add("1");
//        vertices.add("2");
//        vertices.add("t");
//
//        
//        VertexNameInputFram.g = new Graph(vertices);
//        VertexNameInputFram.g.vertexNum = 4;
//        
//        
//        VertexNameInputFram.g.addEdge("s", "1", 3);
//        VertexNameInputFram.g.addEdge("s", "2", 2);
//        VertexNameInputFram.g.addEdge("1", "2", 5);
//        VertexNameInputFram.g.addEdge("1", "t", 2);
//        VertexNameInputFram.g.addEdge("2", "t", 3);
//
//        
//        EdgeInputFram.directedGraph.addEdge("3","s", "1");
//        EdgeInputFram.directedGraph.addEdge("2","s", "2");
//        EdgeInputFram.directedGraph.addEdge("5","1", "2");
//        EdgeInputFram.directedGraph.addEdge("*2","1", "t");
//        EdgeInputFram.directedGraph.addEdge("*3","2", "t");
//
//        
//        
//        EdgeInputFram.map.put("3", "s 1");
//        EdgeInputFram.map.put("2", "s 2");
//        EdgeInputFram.map.put("5", "1 2");
//        EdgeInputFram.map.put("*2", "1 t");
//        EdgeInputFram.map.put("*3", "2 t");



        
        //sheel el comment
        
//        Vector<String> vertices = new Vector<>();
//        vertices = VertexNameInputFram.g.getVertices();
//
//       
//            for (int i = 0; i < vertices.size(); i++) {
//                directedGraph.addVertex(vertices.get(i));
//            }
//        
       // System.out.println(g.getVertices());



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        finishBt = new javax.swing.JButton();
        enterInitialLab = new javax.swing.JLabel();
        enterTerminalLab = new javax.swing.JLabel();
        initialVertex = new javax.swing.JTextField();
        terminalVertex = new javax.swing.JTextField();
        enterEdgeBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        greenTx = new javax.swing.JLabel();
        bluTx2 = new javax.swing.JLabel();
        enterTerminalLab1 = new javax.swing.JLabel();
        weightTx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Here to Enter Edges");

        finishBt.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        finishBt.setForeground(new java.awt.Color(255, 51, 51));
        finishBt.setText("Finish");
        finishBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtActionPerformed(evt);
            }
        });

        enterInitialLab.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        enterInitialLab.setText("Initial Vertex ");

        enterTerminalLab.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        enterTerminalLab.setText("Terminal Vertex");

        initialVertex.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        initialVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialVertexActionPerformed(evt);
            }
        });

        terminalVertex.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        terminalVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalVertexActionPerformed(evt);
            }
        });

        enterEdgeBt.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        enterEdgeBt.setText("Add Edge ");
        enterEdgeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterEdgeBtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setText("After Add All Edges Press Finish");

        greenTx.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        greenTx.setForeground(new java.awt.Color(0, 204, 0));
        greenTx.setText("Edge 1 Added Successfully,You Can Add More");

        bluTx2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        bluTx2.setForeground(new java.awt.Color(0, 0, 255));
        bluTx2.setText("Enter Edge 1");

        enterTerminalLab1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        enterTerminalLab1.setText("Edge Weight");

        weightTx.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        weightTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterInitialLab)
                            .addComponent(initialVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(bluTx2)
                            .addComponent(enterTerminalLab)
                            .addComponent(terminalVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(weightTx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterTerminalLab1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(greenTx)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(enterEdgeBt)
                                .addGap(70, 70, 70)
                                .addComponent(finishBt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enterTerminalLab, terminalVertex});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enterInitialLab, initialVertex});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enterEdgeBt, finishBt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(bluTx2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(enterInitialLab)
                    .addComponent(enterTerminalLab)
                    .addComponent(enterTerminalLab1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initialVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminalVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(greenTx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterEdgeBt)
                    .addComponent(finishBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {enterInitialLab, enterTerminalLab, enterTerminalLab1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {initialVertex, terminalVertex, weightTx});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {enterEdgeBt, finishBt});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialVertexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialVertexActionPerformed

    private void terminalVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalVertexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminalVertexActionPerformed

    private void finishBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtActionPerformed
        // TODO add your handling code here:

            int counter = 1;
            edges = VertexNameInputFram.g.getEdges();
            for (int i = 0; i < edges.size(); i++) {
               
                String src = String.valueOf(edges.get(i).initial);
                String dest = String.valueOf(edges.get(i).terminate);
                String weight = String.valueOf(edges.get(i).weight);
                

                while(edgeNamesArr.contains(weight)){weight+="*" ;}
                edgeNamesArr.add(weight);
                System.out.println("edges = " + edges.get(i).initial +" " +edges.get(i).terminate
                       +" "+edges.get(i).weight );
                directedGraph.addEdge(weight,src,dest);
                
                String mapValue = edges.get(i).initial + " " + edges.get(i).terminate;
                map.put(weight, mapValue);
                
                counter++;
                
            }
            displayGraph();
                        
            
            
            super.setVisible(false);
            ChooseFram chooseFram = new ChooseFram();
            chooseFram.setVisible(true);                

            

           // }           
            
            
     //   }
    }//GEN-LAST:event_finishBtActionPerformed
    public static void displayGraph(){
        vs =
               new VisualizationImageServer<String, String>(new CircleLayout<String, String>(EdgeInputFram.directedGraph), 
                       new Dimension(200, 200));

           
            
            Transformer<String, String> transformer2 = new Transformer<String, String>() {

                @Override
                public String transform(String arg0) {
                    return arg0;
                }

            };



            Transformer<String, String> transformer1 = new Transformer<String, String>() {

                @Override
                public String transform(String arg0){
                    return arg0;
                }
            };
            
       
            

         // vv is the VirtualizationViewer
            vs.getRenderContext().setLabelOffset(20);
            vs.getRenderContext().setEdgeLabelTransformer(transformer1);
            vs.getRenderContext().setVertexLabelTransformer(transformer2);

            
            
            
            frame = new JFrame();
            frame.getContentPane().add(vs);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
            frame.setSize(500,400);
            frame.setTitle("The Graph Input");

            //frame.setLocationRelativeTo(null);
            //int lebar = this.getWidth()/2;
            //int tinggi = this.getHeight()/2;
            int x = (Toolkit.getDefaultToolkit().getScreenSize().width/3)-500;
            int y = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-220;
            frame.setLocation(x, y);


    }
    private void enterEdgeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterEdgeBtActionPerformed
        // TODO add your handling code here:
                

        boolean numeric = false;
        int weight = 0 , dest = 0; 
        try {
            weight = Integer.parseInt(weightTx.getText());
            //dest = Integer.parseInt(terminalVertex.getText());
        } catch (NumberFormatException e) {
            numeric = true;
        }

    
        if(Objects.equals(initialVertex.getText(), "") || Objects.equals(terminalVertex.getText(), "") ){
            JOptionPane.showMessageDialog(this, "Please fill requirements ",  
                       "WARNING", JOptionPane.WARNING_MESSAGE); 
        }
        else if(!VertexNameInputFram.g.vertices.contains(initialVertex.getText()) || 
                !VertexNameInputFram.g.vertices.contains(terminalVertex.getText())
                ){
            JOptionPane.showMessageDialog(this, "You must enter one of the vertices name\n "+ VertexNameInputFram.g.vertices,  
           "ERROR", JOptionPane.ERROR_MESSAGE); 

        }
        else if(numeric){
            JOptionPane.showMessageDialog(this, "You must Enter Integer ",  
           "ERROR", JOptionPane.ERROR_MESSAGE); 

        }
        else{
            
           VertexNameInputFram.g.addEdge(initialVertex.getText(),terminalVertex.getText(),Integer.parseInt(weightTx.getText()));
           //directedGraph.addEdge( weightTx.getText(),initialVertex.getText(), terminalVertex.getText());
           

//            enterInitialLab.setVisible(false);
//            enterTerminalLab.setVisible(false);
//            initialVertex.setVisible(false);
//            terminalVertex.setVisible(false);
//            enterEdgeBt.setVisible(false);
            greenTx.setVisible(false);
            greenTx.setText("Edge "+ counter +" Added Successfully,You Can Add More");
            greenTx.setVisible(true);
            finishBt.setEnabled(true);

            initialVertex.setText("");
            terminalVertex.setText("");
            weightTx.setText("");
         
            counter++;
            bluTx2.setText("Enter Edge "+ counter);

            
        }

    }//GEN-LAST:event_enterEdgeBtActionPerformed

    private void weightTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdgeInputFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdgeInputFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdgeInputFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdgeInputFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdgeInputFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bluTx2;
    private javax.swing.JButton enterEdgeBt;
    private javax.swing.JLabel enterInitialLab;
    private javax.swing.JLabel enterTerminalLab;
    private javax.swing.JLabel enterTerminalLab1;
    private javax.swing.JButton finishBt;
    private javax.swing.JLabel greenTx;
    private javax.swing.JTextField initialVertex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField terminalVertex;
    private javax.swing.JTextField weightTx;
    // End of variables declaration//GEN-END:variables
    public static DirectedSparseGraph<String, String> directedGraph = new DirectedSparseGraph<String, String>();
    public SparseGraph<String, String> unDirectedGraph = new SparseGraph<String, String>();
    public int counter = 1 ;
    public ArrayList<String> edgeNamesArr = new ArrayList();
    public Vector <Edge> edges = new Vector<>();
    public static Map map = new HashMap();
    public static VisualizationImageServer<String, String> vs;
    public static JFrame frame ;



}
