/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algorithms.project;

import edu.uci.ics.jung.graph.SparseGraph;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class VertexNameInputFram extends javax.swing.JFrame {

    /**
     * Creates new form GtaphInput
     */
    public VertexNameInputFram() {
        initComponents();
       // vn = MainFram.verticesNumber;
        setLocationRelativeTo(null);
        finish.setEnabled(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vertexNametx = new javax.swing.JTextField();
        addVertex = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setText("Enter name of vertex 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 11, 270, 31));

        vertexNametx.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        vertexNametx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertexNametxActionPerformed(evt);
            }
        });
        getContentPane().add(vertexNametx, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 54, 145, -1));

        addVertex.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        addVertex.setText("Add Vertex");
        addVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVertexActionPerformed(evt);
            }
        });
        getContentPane().add(addVertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 151, -1, 31));

        finish.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        finish.setForeground(new java.awt.Color(200, 0, 0));
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        getContentPane().add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 151, 121, 31));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("After Add All Edges Press Finish");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 103, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algorithms/project/source/abstract-geometric-shape-connection-with-3d-cubes-background_42705-105.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vertexNametxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertexNametxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vertexNametxActionPerformed

    private void addVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVertexActionPerformed
        // TODO add your handling code here:
            if (vertexNametx.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please Enter Vertex name",  
                "ERROR", JOptionPane.ERROR_MESSAGE); 

            }
            else if(!vertices.contains(vertexNametx.getText())){
                //if(vn != 0){
                    vertices.add(vertexNametx.getText());
                    vertexNametx.setText("");
               // }

                //vn--;
               // if(vn == 0){
//                    EdgeInputFram EIF = new EdgeInputFram();
//                    EIF.setVisible(true);         
//                    super.setVisible(false);


              //  }
                counter++;
                jLabel1.setText("Enter name of vertex "+ counter);
                finish.setEnabled(true);

            }
            else{
                JOptionPane.showMessageDialog(this, "You must enter name not exist here\n "+ vertices,  
           "ERROR", JOptionPane.ERROR_MESSAGE); 

            }
        
    }//GEN-LAST:event_addVertexActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        g = new Graph(vertices);
        EdgeInputFram EIF = new EdgeInputFram();
        EIF.setVisible(true);         
        super.setVisible(false);
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VertexNameInputFram().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVertex;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField vertexNametx;
    // End of variables declaration//GEN-END:variables
    public String vertixName;
    public int vn;
    public int vnVer = 0 ;
    public int counter = 1;
    public static SparseGraph<String, String> unDirectedGraph = new SparseGraph<String, String>();
    public static Graph g;
    public Vector <String> vertices = new Vector<>();

}
